import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-6xl">
            bc-leaks 2.0
          </h1>
          <div className="text-2xl text-white">
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}
          </div>
          <div>
            {!isSignedIn && <SignInButton />}
            {!!isSignedIn && <UserButton />}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
